### ISSUE TITLE
Edit GUI Locations not working

### ISSUE THREAD

**Issue by Cata50** [MrFast-js/SkyblockFeatures#3]
I was able to do this last night w/ like 500 clicks for it to finally select but today it just isn't selecting it, not sure if mod conflict, mod list if needed

https://github.com/MrFast-js/SkyblockFeatures/assets/149321663/1d2004b6-625d-4b09-b5fc-684da9694130

![image](https://github.com/MrFast-js/SkyblockFeatures/assets/149321663/b97ca50e-de6f-4850-aaff-7b81eccab101)

**Comment by MrFast-js** [comment]
Hello, this is a bug due to the GUI scale being on the largest side, to make it act correctly use GUI scale: Normal, if you want to keep the larger GUI scale then currently the overlay features will not be available to you. This will be worked on with a fix not sure when it will happen.

**Comment by MrFast-js** [comment]
This has been fixed
